"""Trajectory codec interfaces, representations, and serialization hooks."""

from kinematicweave.codecs.exact import (
    decode_source_endpoint_states,
    encode_scenario_exact,
    encode_trajectory_exact,
    evaluate_segment,
    replay_timestamps,
    replay_track,
)
from kinematicweave.codecs.hermite import (
    HermiteCodecConfig,
    encode_canonical_parquet_hermite,
    encode_scenario_hermite,
    encode_trajectory_hermite,
    hermite_encoder_parameters_identity,
    summarize_hermite_tape,
    validate_hermite_replay,
    verify_hermite_artifacts,
)
from kinematicweave.codecs.piecewise_linear import (
    PiecewiseLinearCodecConfig,
    ReplayValidationSummary,
    encode_canonical_parquet_piecewise_linear,
    encode_scenario_piecewise_linear,
    encode_trajectory_piecewise_linear,
    encoder_parameters_identity,
    summarize_piecewise_linear_tape,
    validate_piecewise_linear_replay,
    verify_piecewise_linear_artifacts,
)
from kinematicweave.codecs.velocity_bounded import (
    EncodingPerformanceStats,
    VelocityBoundedCodecConfig,
    encode_canonical_parquet_velocity_bounded,
    encode_scenario_velocity_bounded,
    encode_scenario_velocity_bounded_with_performance,
    encode_trajectory_velocity_bounded,
    encode_trajectory_velocity_bounded_with_performance,
    summarize_velocity_bounded_tape,
    validate_velocity_bounded_replay,
    velocity_bounded_encoder_parameters_identity,
    verify_velocity_bounded_artifacts,
)

__all__ = [
    "EncodingPerformanceStats",
    "HermiteCodecConfig",
    "PiecewiseLinearCodecConfig",
    "ReplayValidationSummary",
    "VelocityBoundedCodecConfig",
    "decode_source_endpoint_states",
    "encode_canonical_parquet_hermite",
    "encode_canonical_parquet_piecewise_linear",
    "encode_canonical_parquet_velocity_bounded",
    "encode_scenario_exact",
    "encode_scenario_hermite",
    "encode_scenario_piecewise_linear",
    "encode_scenario_velocity_bounded",
    "encode_scenario_velocity_bounded_with_performance",
    "encode_trajectory_exact",
    "encode_trajectory_hermite",
    "encode_trajectory_piecewise_linear",
    "encode_trajectory_velocity_bounded",
    "encode_trajectory_velocity_bounded_with_performance",
    "encoder_parameters_identity",
    "evaluate_segment",
    "hermite_encoder_parameters_identity",
    "replay_timestamps",
    "replay_track",
    "summarize_hermite_tape",
    "summarize_piecewise_linear_tape",
    "summarize_velocity_bounded_tape",
    "validate_hermite_replay",
    "validate_piecewise_linear_replay",
    "validate_velocity_bounded_replay",
    "velocity_bounded_encoder_parameters_identity",
    "verify_hermite_artifacts",
    "verify_piecewise_linear_artifacts",
    "verify_velocity_bounded_artifacts",
]
